### ISSUE TITLE
sphinx documentation fixes

### ISSUE THREAD

**Issue by iulusoy** [BenTho-Uni/ssc_course_team4#12]
There are a few items that prevent sphinx from working properly:

- Sphinx actually runs all code that is not self-contained. So everything that is not within a function or class definition will be executed, and if there are errors, the sphinx build will fail. The problem was the import statement for io_layer in statistical and numerical; if you adjust that to the standard `import io_layer as io` then the docstrings in those two modules will be compiled and included in the sphinx documentation.
- There are duplicated files: `io_layer.rst`, `modules.rst`, `numerical.rst`, `statistical.rst` live both in the `doc/` folder and in the `doc/source/` folder. I recommend to remove the ones in the `doc/` folder.
- If you include `modules` in your `index.rst`, the initial page will also look nicer:
```
.. toctree::
   :maxdepth: 2
   :caption: Contents:

   modules
```

If you want, you can add me as collaborator and I can push the changes that I made to the `to_check` branch. That may make things clearer.

**Comment by BenTho-Uni** [comment]
Thanks! 
I managed to fix it and the documentation works now through readthedocs.
